version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  Test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14.17.0'
      - run: yarn install --frozen-lockfile
      - run: yarn test

workflows:
  Unit Test:
    jobs:
      - Test
