name: ci

on:
  push:
    branches: ['main']
    paths-ignore:
      - '.github/workflows/release.yml'
  pull_request:
    branches: ['main']
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            react-smartkeys/node_modules
            example/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
            react-smartkeys/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.sha }}

      - run: yarn install --frozen-lockfile 2> >(grep -v warning 1>&2)

      - run: yarn workspaces run prepare

  test:
    needs: [build]
    name: test + coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            react-smartkeys/node_modules
            example/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
            react-smartkeys/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.sha }}

      - uses: actions/cache@v3
        with:
          path: |
            react-smartkeys/__snapshots__
          key: snapshots-${{ hashFiles('yarn.lock') }}-${{ hashFiles('smartkey.tsx') }}-${{ hashFiles('smartkey.test.tsx') }}
          restore-keys: |
            snapshots-${{ hashFiles('yarn.lock') }}-${{ hashFiles('smartkey.tsx') }}-${{ hashFiles('smartkey.test.tsx') }}

      - run: yarn workspaces run test:unit --updateSnapshots=$([[ $(git branch --show-current) == "main" ]] && echo true || echo false)

  lint:
    needs: [build]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            react-smartkeys/node_modules
            example/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
            react-smartkeys/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.sha }}

      - run: yarn workspaces run test:lint

  format:
    needs: [build]
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            react-smartkeys/node_modules
            example/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}

      - run: yarn workspaces run test:format
