name: ci

on:
  push:
    branches: ['main']
    paths-ignore:
      - '.github/workflows/release.yml'
  pull_request:
    branches: ['main']
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - run: yarn add react@${{ matrix.react }}
        working-directory: package

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            package/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}

      - uses: actions/cache@v3
        with:
          path: |
            package/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}-${{ matrix.react }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}-${{ matrix.react }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - run: yarn install --frozen-lockfile 2> >(grep -v warning 1>&2)
      - run: yarn workspaces run prepare

  test:
    needs: [build]
    name: test + coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            package/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}

      - uses: actions/cache@v3
        with:
          path: |
            package/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}-${{ matrix.react }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}-${{ matrix.react }}

      - uses: actions/cache@v3
        with:
          path: |
            package/__snapshots__
          key: snapshots-${{ hashFiles('yarn.lock') }}-${{ hashFiles('smartkey.tsx') }}-${{ hashFiles('smartkey.test.tsx') }}-${{ matrix.react }}
          restore-keys: |
            snapshots-${{ hashFiles('yarn.lock') }}-${{ hashFiles('smartkey.tsx') }}-${{ hashFiles('smartkey.test.tsx') }}-${{ matrix.react }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0

      - run: yarn workspaces run test:unit --updateSnapshots=$([[ $(git branch --show-current) == "main" ]] && echo true || echo false)

  lint:
    needs: [build]
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            package/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}

      - uses: actions/cache@v3
        with:
          path: |
            package/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0

      - run: yarn workspaces run test:lint

  format:
    needs: [build]
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            package/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}-18.12.1-18.x
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}-${{ matrix.react }}-18.12.1-18.x

      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0

      - run: yarn workspaces run test:format
