name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Type'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
          - from-git
      pi:
        description: 'Pre-release identifier'
        required: true
        default: 'alpha'
        type: string

jobs:
  preflight-checks:
    uses: ./.github/workflows/ci.yml

  publish-npm:
    needs: [preflight-checks]
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            package/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
            package/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}

      - run: cp README.md package/README.md

      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
          registry-url: https://registry.npmjs.org/

      - uses: JS-DevTools/npm-publish@v1
        continue-on-error: true
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          registry: https://registry.npmjs.org/
          package: ./package/package.json
          access: public
          check-version: true

  publish-github:
    needs: [preflight-checks]
    name: publish to github packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            package/node_modules
          key: dependencies-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            dependencies-${{ hashFiles('yarn.lock') }}

      - uses: actions/cache@v3
        with:
          path: |
            package/dist
          key: build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            build-${{ hashFiles('yarn.lock') }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}

      - run: cp README.md package/README.md

      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
          registry-url: https://npm.pkg.github.com

      - run: node prepare-github-packages.js @aifrim/react-smartkeys

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GH_PUBLISH }}
          registry: https://npm.pkg.github.com
          package: ./package/package.json
          access: public
          check-version: true

  release:
    needs: [publish-npm, publish-github]
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
